# .air.toml
root = "cmd/main"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/main/main.go"
bin = "./tmp/main"
include = [".go", ".mod"]
exclude = ["tmp/*", "vendor/*"]

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
